
server:
  port: 1010
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 2
        permittedNumberOfCallsInHalfOpenState: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 2s
        failureRateThreshold: 50
  retry:
    instances:
      callExternalServiceRetry:
        maxAttempts: 2 # حداکثر تعداد تلاش‌ها
        waitDuration: 1s # مدت زمان انتظار بین تلاش‌ها
        retryExceptions:
            - org.springframework.web.client.ResourceAccessException # خطاهایی که باعث Retry می‌شون
  ratelimiter:
    instances:
      callExternalServiceRateLimiter:
        limit-for-period: 1 # تعداد درخواست‌های مجاز در هر بازه زمانی
        limit-refresh-period: 10s # بازه زمانی که در آن درخواست‌ها محدود می‌شوند
        timeout-duration: 1s # حداکثر زمانی که درخواست منتظر می‌ماند تا محدودیت برداشته ش
  timelimiter:
    instances:
      callExternalServiceTimeLimiter:
        timeout-duration: 2s  # مدت زمانی که متد می‌تواند اجرا شود
        cancel-running-future: true  # لغو عملیات در حال اجرا در صورت تجاوز از زمان تعیین‌شده